# Generated by Django 4.2.1 on 2023-06-10 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='updated',
            field=models.DateField(blank=True, null=True),
        ),
    ]
