# Generated by Django 4.2.1 on 2023-06-02 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_post_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='snippet',
            field=models.CharField(blank=True, default='Dit is een samenvatting van de blogpost', max_length=255, null=True),
        ),
    ]
